### ISSUE TITLE
Destinos Soñados

### ISSUE THREAD

**Issue by amf1014** [nrc1008/Practica1_Enunciado2#1]
- [ ] Italia 
- [ ] Francia
- [ ] Suiza
- [ ] Países Bajos
- [ ] Austria
- [x] Noruega
- [x] Islas Griegas

**Comment by nrc1008** [comment]
- [x] Noruega
- [x] Grecia
- [ ] Dinamarca
- [ ] Letonia
- [x] Polonia
- [ ] Estonia

**Comment by mga1038** [comment]
- [x] Grecia
- [x] Noruega
- [ ] Rusia 
- [x] Suiza
- [ ] Irlanda
