### ISSUE TITLE
Destinos visitados

### ISSUE THREAD

**Issue by nrc1008** [nrc1008/Practica1_Enunciado2#2]
- [x] Francia
- [ ] Italia
- [ ] Bruselas
- [ ] Luxemburgo
- [x] Portugal
- [ ] Países Bajos

**Comment by amf1014** [comment]
- [x] Reino Unido
- [ ] Alemania
- [ ] Portugal
- [ ] Irlanda
- [ ] Luxemburgo

**Comment by mga1038** [comment]
- [x] Portugal
- [ ] Francia
- [x] Alemania
- [x] Reino Unido
