### ISSUE TITLE
Desición destino

### ISSUE THREAD

**Issue by amf1014** [nrc1008/Practica1_Enunciado2#3]
Hola chicas,
Entre los dos destinos que estén seleccionados por los tres, hacemos sorteo entre los más deseados. ¿Les parece bien?

**Comment by nrc1008** [comment]
Sii! Me encantaría ir a Grecia o a Noruega, y he visto que a vosotros también , jaja. Conozco una aplicación de sorteos, esta tarde hablamos y lo hacemos. Que ganas de organizar el viaje!

**Comment by mga1038** [comment]
Hola chicos! Me encanta que hay salido Noruega, tengo muchas ganas de ir!
