### ISSUE TITLE
Buscar mejor vuelo

### ISSUE THREAD

**Issue by amf1014** [nrc1008/Practica1_Enunciado2#4]
Si les parece, ya que hemos elegido el destino, podemos cada uno buscar en una web distinta de viajes el mejor precio de vuelo y, así cuadramos fechas.

**Comment by nrc1008** [comment]
<img width="837" alt="Captura de pantalla 2024-03-10 a les 12 24 49" src="https://github.com/nrc1008/Practica1_Enunciado2/assets/162798295/fcaef7fb-bbad-4521-99d0-28d3c39c4cb3">

He encontrado este vuelo para el finde del 15 de marzo, entre todas las opciones buscadas es el más económico, y es directo! Si buscáis distintas y mejores, avisad!

**Comment by amf1014** [comment]
<img width="303" alt="Captura de pantalla 2024-03-10 a las 12 34 11" src="https://github.com/nrc1008/Practica1_Enunciado2/assets/162733005/9d354380-c121-4e60-ab1f-662602bd868b">

Yo he encontrado este vuelo en una compañía de vuelos Noruega y veo que es barato y sale desde Barcelona. Igualmente, creo que es mejor tu opción.

**Comment by mga1038** [comment]
He estado buscando pero todas las opciones eran más caras que las que habéis sugerido vosotros. La opción de Nia me parece la mejor, barata y directa!
