### ISSUE TITLE
Buscar mejor hotel

### ISSUE THREAD

**Issue by nrc1008** [nrc1008/Practica1_Enunciado2#5]
Yo me encargo de buscar alojamiento, iré poniendo las mejores opciones y vamos decidiendo en conjunto. Si encontráis algo decidme!

**Comment by nrc1008** [comment]
<img width="794" alt="Captura de pantalla 2024-03-10 a les 12 29 50" src="https://github.com/nrc1008/Practica1_Enunciado2/assets/162798295/1c55f7e6-9dbf-4c33-999c-bb722b30270a">

Esta opción parece buena, y a muy buen precio entre los tres, siendo un total de 49€ por persona las dos noches. ¿Qué opinais?

**Comment by amf1014** [comment]
Me gusta mucho el apartamento y el precio. Sin embargo, echándole un ojo a la ubicación he visto que tendríamos que gastar en transporte hasta el centro para casi todo. Yo he visto este Airbnb que está bastante bien:

<img width="569" alt="Captura de pantalla 2024-03-10 a las 12 49 04" src="https://github.com/nrc1008/Practica1_Enunciado2/assets/162733005/1d029615-51b4-44bd-be14-9c0ed88572e2">

**Comment by mga1038** [comment]
Siento no aportar mucho en este apartado, pero soy malísima buscando ofertas. El apartamento que ha sugerido Adrián me parece la mejor opción, hay que invertir un poco más pero lo ahorramos en transporte. Qué ganas de ir!
