### ISSUE TITLE
Ocio

### ISSUE THREAD

**Issue by mga1038** [nrc1008/Practica1_Enunciado2#8]
Hola chicos, como nos gusta mucho la noche, he pensado en buscar actividades nocturnas por Oslo para conocer la ciudad desde otro punto de vista.

1. Posthallen Drinkhub, es un pub alternativo famoso por sus copas
<img width="782" alt="Captura de pantalla 2024-03-10 150128" src="https://github.com/nrc1008/Practica1_Enunciado2/assets/162734054/c860d314-f100-4154-8296-a3adbad06367">

2. Club de comedia, para echarnos unas risas mientras nos tomamos unas cervezas
<img width="780" alt="Captura de pantalla 2024-03-10 150419" src="https://github.com/nrc1008/Practica1_Enunciado2/assets/162734054/68d5271a-8fb2-4dce-80a0-0dbbf2913166">

3. Olso camping, un camping de golf con bar, para pasar el rato y conocer gente.
<img width="784" alt="Captura de pantalla 2024-03-10 150558" src="https://github.com/nrc1008/Practica1_Enunciado2/assets/162734054/6ae19bc5-1aa4-43c8-88de-4fc545360793">

**Comment by nrc1008** [comment]
Parecen las tres súper divertidas!!

**Comment by amf1014** [comment]
Me encantan las las actividades!!
